### ISSUE TITLE
No Longer Working (Dec.2018)

### ISSUE THREAD

**Issue by waveely** [rolandas-valantinas/gists#1]
Used to work but no longer.
Will there be an update?

![remove ranged listings not work](https://user-images.githubusercontent.com/31081103/49807211-7eefd980-fd27-11e8-91c1-f5fe501ae0ca.PNG)

**Comment by rolandas-valantinas** [comment]
Sorry for late reply. Might be specific category view preventing it from working

![awesomescreenshot-2019-02-05t22-12-29-546z](https://user-images.githubusercontent.com/6222540/52307774-75839600-2993-11e9-85df-57fec311c206.gif)
Still works in normal view

**Comment by rolandas-valantinas** [comment]
Closing down as it still works in expected layout - only lists not tiles while using search
