### ISSUE TITLE
FB Marketplace script has stop working after ~5 attempts

### ISSUE THREAD

**Issue by LightMoon** [rolandas-valantinas/gists#2]
Hi,

When I run the script and 4 ~ 5 attempts, I will encounter to black page.

I think, FB detects it and block it I there something I can do to get it fixed?

Thanks

**Comment by rolandas-valantinas** [comment]
Hi, there are some ongoing issues with FB marketplace itself (distance filter no longer works on my personal account but works on work one). As soon as they fix their end I'll address my script. For me Tampermonkey is not even creating filter controls at all.

**Comment by rolandas-valantinas** [comment]
So my marketplace started working properly again and I've tested extension
I've used this url for testing https://www.facebook.com/marketplace/coventry/home/?sort=CREATION_TIME_DESCEND
Script looped more than 10 times on this page and worked as it should. Could you test again and maybe create a GIF of script failing, please?

**Comment by rolandas-valantinas** [comment]
Closing as it is stale
